# Generated by Django 5.1 on 2025-02-05 07:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Tur",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100)),
                ("manzil", models.CharField(max_length=200)),
                ("narx", models.DecimalField(decimal_places=2, max_digits=10)),
                ("boshlanish_sana", models.DateField()),
                ("tugash_sana", models.DateField()),
                ("tasvir", models.ImageField(blank=True, upload_to="tur_tasvirlari/")),
            ],
        ),
        migrations.CreateModel(
            name="Bron",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bron_sanasi", models.DateTimeField(auto_now_add=True)),
                ("yolovchilar_soni", models.PositiveIntegerField()),
                ("umumiy_narx", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "foydalanuvchi",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="tur.tur"
                    ),
                ),
            ],
        ),
    ]
